pages:
  stage: build
  image: python:2

  before_script:
    - pip install -r requirements.txt

  script:
    - mkdir -p public/netapp-events
    - cd docs && make html
    - cp -r _build/html/* ../public/netapp-events
  artifacts:
    paths:
      - public

