pages:
  stage: build
  image: python:2

  before_script:
    - pip install -r requirements.txt

  script:
    - mkdir -p public/netapp-events
    - cd docs && make html
    - cp -r _build/html ../public/netapp-events
  artifacts:
    paths:
      - public

# Deploy the pages generated to DFS
dfsdeploy:
  # Executed during the deploy stage
  stage: deploy
  # Only when the master branch is pushed
  only:
    - master
  # Custom docker image providing the needed tools to deploy in DFS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  # Script that performs the deploy to DFS. Makes use of the variables defined in the project
  # It will not sync the generated content with the folder in DFS (risk of deleting DFS management files)
  # It will just override the contents of DFS or copy new files
  - deploy-dfs
