language: python
python:
  - "2.7"

# script: bash ./deploy.sh
before_install:
  - pip install coveralls
install: "pip install -r requirements.txt"
script: pytest netapp/tests/test_vocabulary.py
after_success:
  - coveralls

# env:
#   global:
#    - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
#    - COMMIT_AUTHOR_EMAIL: "albin.stjerna@cern.ch"
