language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_10739f0a1b0b_key -iv $encrypted_10739f0a1b0b_iv
  -in deploy_github_netapp.enc -out deploy_github_netapp -d
- pip install coveralls
env:
  global:
    - ENCRYPTION_LABEL: "10739f0a1b0b"
    - COMMIT_AUTHOR_EMAIL: "albin.stjerna@cern.ch"
install: pip install -r requirements.txt
script:
  - pytest netapp/tests/test_vocabulary.py
after_success:
  - coveralls
  - cd doc && make clean && make html
  - bash ./deploy.sh docs/_build/html
