language: python
python:
- '2.7'
- '3.6'
cache:
  pip: true
before_install:
- openssl aes-256-cbc -K $encrypted_1c6dda9558d1_key -iv $encrypted_1c6dda9558d1_iv
  -in cassettes.tar.gz.enc -out cassettes.tar.gz -d
- openssl aes-256-cbc -K $encrypted_10739f0a1b0b_key -iv $encrypted_10739f0a1b0b_iv
  -in deploy_github_netapp.enc -out deploy_github_netapp -d
- pip install coveralls
- tar -xf cassettes.tar.gz -C netapp/tests/
env:
  global:
  - ENCRYPTION_LABEL: 10739f0a1b0b
  - COMMIT_AUTHOR_EMAIL: albin.stjerna@cern.ch
install: pip install -r requirements.txt
script:
- pytest
after_success:
- coveralls
- cd docs && make clean && make html && cd ..
- bash ./deploy.sh docs/_build/html
